import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import { CommandProvider } from "@/providers/CommandProvider";
import { ToastProvider } from "@/providers/ToastProvider";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";

const inter = Inter({
    subsets: ["latin", "latin-ext"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();
    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={cx(inter.variable, "bg-primary antialiased")}>
                <NextIntlClientProvider messages={messages}>
                    <ConvexClientProvider>
                        <RouteProvider>
                            <Theme>
                                <CommandProvider>
                                    {children}
                                    <ToastProvider />
                                </CommandProvider>
                            </Theme>
                        </RouteProvider>
                    </ConvexClientProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
